export const metadata = {
  title: "Find Jobs USA",
  description: "Generated by Next.js",
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      {children}
    </div>
  );
}
