export const metadata = {
    title: "Job Details",
    description: "Generated by Next.js",
}

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <div>
            {children}
        </div>
    );
}