export const metadata = {
    title: "React Concepts",
    description: "Generated by Next.js",
  }
  
  export default function Layout({ children }: { children: React.ReactNode }) {
    return (
      <div>
        <h1 className="mb-5">React Concepts Starts</h1>
        {children}
        <h1 className="mt-5">React Concepts Ends</h1>
      </div>
    );
  }
  